#!/usr/bin/env python3
"""One-off: turn Natural Earth 1:110m countries (GeoJSON) into site/assets/world.js.

The map is pre-projected (Natural Earth I, the same formula as d3.geoNaturalEarth1) so the
site needs no mapping library; app code projects city dots with WORLD.project(lon, lat).

  curl -sSL -o ne110.geojson \
    https://cdn.jsdelivr.net/gh/nvkelso/natural-earth-vector@v5.1.2/geojson/ne_110m_admin_0_countries.geojson
  python3 scripts/make_world.py ne110.geojson
"""
import json
import math
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
WIDTH = 1000.0


def raw(lon: float, lat: float) -> tuple[float, float]:
    lam, phi = math.radians(lon), math.radians(lat)
    p2 = phi * phi
    p4 = p2 * p2
    x = lam * (0.8707 - 0.131979 * p2 + p4 * (-0.013791 + p4 * (0.003971 * p2 - 0.001529 * p4)))
    y = phi * (1.007226 + p2 * (0.015085 + p4 * (-0.044475 + 0.028874 * p2 - 0.005916 * p4)))
    return x, -y


def main(src: str) -> None:
    feats = json.loads(pathlib.Path(src).read_text())["features"]
    shapes = {}
    for f in feats:
        p = f["properties"]
        code = p["ISO_A2"] if p["ISO_A2"] != "-99" else p["ISO_A2_EH"]
        if code in ("-99", "AQ") or p["NAME"] == "Antarctica":
            continue
        g = f["geometry"]
        polys = g["coordinates"] if g["type"] == "MultiPolygon" else [g["coordinates"]]
        shapes.setdefault(code, []).extend(polys)

    # Bounds over everything kept (Antarctica dropped), in raw projected units.
    xs, ys = [], []
    for polys in shapes.values():
        for poly in polys:
            for ring in poly:
                for lon, lat in ring:
                    x, y = raw(lon, lat)
                    xs.append(x)
                    ys.append(y)
    x0, x1 = raw(-180, 0)[0], raw(180, 0)[0]
    y0, y1 = min(ys), max(ys)
    k = WIDTH / (x1 - x0)
    height = round((y1 - y0) * k + 8)

    def proj(lon, lat):
        x, y = raw(lon, lat)
        return (x - x0) * k, (y - y0) * k + 4

    out = {}
    for code, polys in sorted(shapes.items()):
        parts = []
        for poly in polys:
            for ring in poly:
                pts = [proj(lon, lat) for lon, lat in ring]
                d = "M" + "L".join(f"{x:.1f},{y:.1f}" for x, y in pts) + "Z"
                parts.append(d)
        out[code] = "".join(parts)

    js = (
        "/* Generated by scripts/make_world.py from Natural Earth 1:110m (public domain). */\n"
        f"window.WORLD = {{w: {WIDTH:.0f}, h: {height}, k: {k:.6f}, x0: {x0:.6f}, y0: {y0:.6f},\n"
        f"  shapes: {json.dumps(out, separators=(',', ':'))}}};\n"
        "window.WORLD.project = function (lon, lat) {\n"
        "  var lam = lon * Math.PI / 180, phi = lat * Math.PI / 180, p2 = phi * phi, p4 = p2 * p2;\n"
        "  var x = lam * (0.8707 - 0.131979 * p2 + p4 * (-0.013791 + p4 * (0.003971 * p2 - 0.001529 * p4)));\n"
        "  var y = -phi * (1.007226 + p2 * (0.015085 + p4 * (-0.044475 + 0.028874 * p2 - 0.005916 * p4)));\n"
        "  return [(x - this.x0) * this.k, (y - this.y0) * this.k + 4];\n"
        "};\n"
    )
    dst = ROOT / "site" / "assets" / "world.js"
    dst.write_text(js, encoding="utf-8")
    print(f"wrote {dst} ({len(js) / 1024:.0f} KB, {len(out)} countries, {WIDTH:.0f}x{height})")


if __name__ == "__main__":
    main(sys.argv[1])
